spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SimonShaw25/springCloudConfig/
          search-paths: config
          username: SimonShaw25  #账号密码写真实的快一些我觉得，不使用也能访问有点慢
          password: xzclove123

server:
  port: 8888